"""empty message

Revision ID: 070251352b1b
Revises: 739166295260
Create Date: 2024-10-29 17:06:20.524483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070251352b1b'
down_revision = '739166295260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_assignments')
    op.drop_table('lecturer_assignments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer_assignments',
    sa.Column('lecturer_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('lecturer_id', 'assignment_id')
    )
    op.create_table('lecture_assignments',
    sa.Column('lecture_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('lecture_id', 'assignment_id')
    )
    # ### end Alembic commands ###
