"""empty message

Revision ID: 3ee597d5a4a1
Revises: 42e720aaed38
Create Date: 2024-10-25 03:49:47.155958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee597d5a4a1'
down_revision = '42e720aaed38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_room_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_chat_room', 'chat_room', ['chat_room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_room_id')

    # ### end Alembic commands ###
