"""empty message

Revision ID: 42e720aaed38
Revises: df2e29db3a1a
Create Date: 2024-10-23 22:58:54.296271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e720aaed38'
down_revision = 'df2e29db3a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_community', type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_posts_community', 'communities', ['community_id'], ['id'])

    # ### end Alembic commands ###
