"""empty message

Revision ID: 739166295260
Revises: 764a30440a90
Create Date: 2024-10-29 16:43:55.605055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739166295260'
down_revision = '764a30440a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assignmant', type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_assignmant', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###
