"""empty message

Revision ID: 764a30440a90
Revises: f5cb03430ef7
Create Date: 2024-10-29 05:18:53.185193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764a30440a90'
down_revision = 'f5cb03430ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_view_assisnment', 'users', ['lecturer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lecturer_id')

    # ### end Alembic commands ###
