"""Updated Community and added CommunityMessage model

Revision ID: df2e29db3a1a
Revises: 1c975b71dcf2
Create Date: 2024-10-21 17:43:09.551904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2e29db3a1a'
down_revision = '1c975b71dcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_posts_community', 'communities', ['community_id'], ['id'])  # Added a name for the foreign key

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_community', type_='foreignkey')  # Use the name of the foreign key here
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
