"""empty message

Revision ID: f5cb03430ef7
Revises: 3ee597d5a4a1
Create Date: 2024-10-29 03:37:08.004157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cb03430ef7'
down_revision = '3ee597d5a4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key('fk_assignmant', 'users', ['student_id'], ['id'])

    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('notes')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('student_id')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
